### ISSUE TITLE
Info regarding parental information

### ISSUE THREAD

**Issue by sanchari24** [tomoyukif/GBScleanR#2]
Hello, I have data from a GBS experiment from french beans. I as such, do not have the parental line information from the breeders. I was following the tutorial from [http://www.bioconductor.org/packages/release/bioc/vignettes/GBScleanR/inst/doc/BasicUsageOfGBScleanR.html#73_Genotype_estimation](Bioconductor) until the **Section 6** for basic filtering and subsetting. From error correction onwards, is it absolutley necessary to have the parental line information ?
Thanks.

**Comment by sanchari24** [comment]
Another situation we face is that often times we have replicates. If that is also incorporated into the error correction (we expect the same genotype calls among the reps) that will be great

**Comment by sanchari24** [comment]
Hi, if the new features are incorporated, kindly let me know from where I could download the updated package. On the Biocunductor site, it is 1.2.14 version.

Thanks.

**Comment by tomoyukif** [comment]
I"ve uploaded the new version in which the parentless mode was implemented, to Bioconductor and GitHub. Unfortunately, Bioconductor is now preparing to release version 3.17, and the repository of version 3.16 will not get any updates anymore. Please install the new GBScleanR from GitHub using the following code.
`devtools::install_github("tomoyukif/GBScleanR", build_vignettes = TRUE)`
In the new version, you can initialize the scheme object by `initScheme()` without specifying parental samples by `setParents()`.
For example,
```r
# Load your GDS file.
gds <- loadGDS("your.gds")

# Initialize the scheme object without parent information
gds <- initScheme(gds)

# Initializing the scheme object without parents produces offspring with member ID  3 from a pairing of dummy parents. You can add info of the next cross to the scheme by specifying `crosstype = sibling` or `crosstype = selfing`, if needed.
gds <- addScheme(gds, crosstype = "sibling", mating = cbind(c(3, 3)))

# Then, you can run estGeno().
gds <- estGeno(gds)
```

**Comment by tomoyukif** [comment]
For the data with replicates, I will implement the function for it in the next update. Please wait for another couple of weeks

**Comment by tomoyukif** [comment]
This is a quite late response to the request for the function to incorporate replicate information into the genotype estimation step. I finally implemented a new function setReplicates() that allow users to set which samples are replicates. Now you can find more detailed information of the function in the vignette.
